### ISSUE TITLE
Is the website dead?

### ISSUE THREAD

**Issue by skariko** [radude/rentry#14]
Hello,
just want to know if the website rentry.co is definetely down or if it's just in maintenance.

Thanks.

**Comment by alejandro097** [comment]
> Just a technical issue with the main domain. You can use **rentry.org** for now. Working on getting buthe .co version up and running.


But the new .org domain is going to stay right? Like links created now would still work after main domain is up?

**Comment by radude** [comment]
> But the new .org domain is going to stay right? Like links created now would still work after main domain is up?

Yep. The org has been around for a while now and will stay after co is up. They share the same database and everything. Consider it a mirror.
