### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by MechaXYZ** [radude/rentry#27]
Every command I enter results in a 403. I see that you've added Cloudflare to rentry.co, so that's definitely the problem.

**Comment by MechaXYZ** [comment]
I know you could just change the BASE_URL to rentry.org, but you may add Cloudflare to rentry.org as well, so I'm posting this issue.

**Comment by pastelink-official** [comment]
This was during a major DDOS attack, and API access is the first to get blocked by Cloudflare when the security levels go up. Should all be restored now, and working this week to up defenses to make it pointless for the perpetrator to do future attacks.

**Comment by radude** [comment]
This was during a major DDOS attack, and API access is the first to get blocked by Cloudflare when the security levels go up. Should all be restored now, and working this week to up defenses to make it pointless for the perpetrator to do future attacks.

**Comment by MechaXYZ** [comment]
Alright, thanks!
