### ISSUE TITLE
Why doesn't rentry.co wrap lines?

### ISSUE THREAD

**Issue by anonyno** [radude/rentry#6]
Every other website that uses markdown rewraps the lines. For example, I have compared the output of rentry's Markdown engine to that a number of other Markdown implementations.

- [Here is the source of the markdown](https://rentry.co/yim9d/raw)
- [Here is what rentry renders](https://rentry.co/yim9d)
- [Here is what other markdown engines render](https://babelmark.github.io/?text=Testing+the+line+wrapping+in+rentry.%0A%0ALorem+ipsum+dolor+sit+amet%2C+consectetur%0Aadipiscing+elit.+Mauris+et+accumsan%0Aaugue%2C+sed+posuere+odio.+Sed+porta+vitae%0Apurus+ac+convallis.+Duis+vel+nunc+ac%0Aodio+placerat+imperdiet+nec+ut+libero.%0APellentesque+vulputate+blandit+dui.+Ut%0Aac+lacus+arcu.+Vestibulum+auctor+augue%0Avel+arcu+euismod%2C+quis+tincidunt+erat%0Apulvinar.+Maecenas+pharetra+justo+at%0Aenim+pellentesque%2C+in+vehicula+lacus%0Aconsequat.+Duis+a+interdum+purus.%0AVestibulum+imperdiet+nisi+sed+erat%0Avehicula%2C+eget+dapibus+nisi+rutrum.%0AMaecenas+vehicula+ligula+in+fringilla%0Adignissim.++Donec+mollis+accumsan+dui.%0ASed+et+eros+neque.+Aenean+quis+sapien+eu%0Adiam+hendrerit+sollicitudin+at+non%0Apurus.+Duis+volutpat+sem+sem%2C+eu+dapibus%0Ajusto+fermentum+et.+Mauris+nec+pulvinar%0Aodio.%0A)

As you can see, 37 out of the 38 markdown implementations tested in that website put the entire paragraph into a `p` element, rather than adding `br` elements everywhere the user pressed enter in the source. It would make it easier for new users if you did that too.

**Comment by radude** [comment]
Yeah rentry uses line breaks. It is rather popular behavior, just no the default one. 
A lot of the markdown engines have some sort of extension or option for this: [1](https://github.com/erusev/parsedown/wiki/Usage)  [2](https://github.com/markdown-it/markdown-it#init-with-presets-and-options) [3](https://python-markdown.github.io/extensions/nl2br/)

I believe GitHub also uses nl2br but for comments only.
